[tools]
"aqua:casey/just" = "1.46.0"
"aqua:cli/cli" = "2.85.0"
"aqua:evilmartians/lefthook" = "2.0.15"
"aqua:jqlang/jq" = "1.8.1"
"aqua:mikefarah/yq" = "4.50.1"
"go" = "1.25.5"
"yamlfmt" = "0.21.0"

[hooks]
postinstall = [
  "mkdir -p {{config_root}}/.cache",
]
